version: '3.8'
services:
  todo-list:
    build:
      context: .
      dockerfile: dockerfile
    container_name: todo-list
    tty: true
    restart: always
    environment:
      - TZ:Asia/Tokyo
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    # 起動時のカレントフォルダを指定
    working_dir: /app
    # 標準入出力とエラー出力をコンテナに結びつけ
    stdin_open: true
volumes:
  todo-list:
    driver: local